title:             W2tar
email:             starship91@gmial.com
description:       Blog
author:            W
baseurl:           ""
url:               "http://wonsungil.github.io"

# Social Profiles
github_username:   wonsungil
facebook_username: sungil.won.3

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
